const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const g = require("./comment-guard");

const editPayload = (fp, newS, oldS = "") => ({
  tool_name: "Edit",
  tool_input: { file_path: fp, old_string: oldS, new_string: newS },
});
const writePayload = (fp, content) => ({
  tool_name: "Write",
  tool_input: { file_path: fp, content },
});
const noRead = () => "";

test("commentBody: снимает обрамление всех семейств", () => {
  assert.equal(g.commentBody("// привет"), "привет");
  assert.equal(g.commentBody("# привет"), "привет");
  assert.equal(g.commentBody("-- привет"), "привет");
  assert.equal(g.commentBody("/* привет */"), "привет");
  assert.equal(g.commentBody("/** привет */"), "привет");
});

test("commentBody: многострочный блок схлопывается в одну строку", () => {
  assert.equal(g.commentBody("/*\n * первая\n * вторая\n */"), "первая вторая");
});

test("commentBody: пустой комментарий-разделитель → пусто", () => {
  assert.equal(g.commentBody("//"), "");
  assert.equal(g.commentBody("// ───────────"), "───────────");
});

test("isSanctionedComment: канонический русский префикс", () => {
  assert.ok(g.isSanctionedComment("Не менять, потому что statSync виснет"));
  assert.ok(g.isSanctionedComment("не менять потому что порядок значим"));
  assert.ok(g.isSanctionedComment("Не менять — потому что кап в байтах"));
});

test("isSanctionedComment: английский эквивалент для нерусских проектов", () => {
  assert.ok(g.isSanctionedComment("Do not change because order matters"));
  assert.ok(g.isSanctionedComment("Don't change, because the cap is in bytes"));
});

test("isSanctionedComment: префикс без содержания и близкие формы — нет", () => {
  assert.ok(!g.isSanctionedComment("Не менять"));
  assert.ok(!g.isSanctionedComment("Не менять, потому что"));
  assert.ok(!g.isSanctionedComment("не трогать, потому что сломается"));
  assert.ok(!g.isSanctionedComment("тут потому что важно"));
});

test("isExemptComment: функциональные директивы — часть кода", () => {
  for (const d of [
    "eslint-disable-next-line no-console",
    "@ts-expect-error узкий тип",
    "prettier-ignore",
    "type: ignore[arg-type]",
    "noqa: E501",
    "pylint: disable=too-many-locals",
    "nolint",
    "go:generate mockgen",
    "istanbul ignore next",
    "shellcheck disable=SC2086",
    "!/usr/bin/env node",
    "SPDX-License-Identifier: MIT",
    "@generated by protoc",
  ]) {
    assert.ok(g.isExemptComment("// " + d, d), d);
  }
});

test("isExemptComment: JSDoc с тегом — API-док, без тега — проза", () => {
  const withTag = "/**\n * @param {string} a\n */";
  assert.ok(g.isExemptComment(withTag, g.commentBody(withTag)));
  const prose = "/**\n * Тут мы считаем сумму и потом округляем\n */";
  assert.ok(!g.isExemptComment(prose, g.commentBody(prose)));
});

test("isExemptComment: пустой разделитель — не пояснение", () => {
  assert.ok(g.isExemptComment("//", ""));
});

test("addedComments: эхо старого комментария в old_string не считается новым", () => {
  const old = "// пояснение\nfunction a() {}";
  const neu = "// пояснение\nfunction renamed() {}";
  const added = g.addedComments(
    "Edit",
    { file_path: "/r/a.js", old_string: old, new_string: neu },
    noRead,
    "slash",
  );
  assert.deepEqual(added, []);
});

test("addedComments: дописанный второй экземпляр той же строки — добавление", () => {
  const added = g.addedComments(
    "Edit",
    { file_path: "/r/a.js", old_string: "// x", new_string: "// x\n// x" },
    noRead,
    "slash",
  );
  assert.equal(added.length, 1);
});

test("addedComments: Write дифается против содержимого на диске", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cg-"));
  const fp = path.join(dir, "a.js");
  fs.writeFileSync(fp, "// старый\nconst a = 1;\n");
  const added = g.addedComments(
    "Write",
    { file_path: fp, content: "// старый\n// новый\nconst a = 2;\n" },
    g.safeReadFile,
    "slash",
  );
  assert.equal(added.length, 1);
  assert.equal(added[0].body, "новый");
  fs.rmSync(dir, { recursive: true, force: true });
});

test("addedComments: MultiEdit склеивает все правки", () => {
  const added = g.addedComments(
    "MultiEdit",
    {
      file_path: "/r/a.js",
      edits: [
        { old_string: "const a = 1;", new_string: "// раз\nconst a = 2;" },
        { old_string: "const b = 1;", new_string: "// два\nconst b = 2;" },
      ],
    },
    noRead,
    "slash",
  );
  assert.deepEqual(
    added.map((c) => c.body),
    ["раз", "два"],
  );
});

test("addedComments: `//` внутри строки и template literal — не комментарий", () => {
  const src = [
    'const url = "https://example.com";',
    "const fixture = `",
    "  // это код в фикстуре теста",
    "`;",
  ].join("\n");
  const added = g.addedComments(
    "Edit",
    { file_path: "/r/a.test.js", old_string: "", new_string: src },
    noRead,
    "slash",
  );
  assert.deepEqual(added, []);
});

test("addedComments: `#` внутри python-docstring и строки — не комментарий", () => {
  const src = [
    "def f():",
    '    """',
    "    # заголовок в докстринге",
    '    """',
    "    s = '# not a comment'",
  ].join("\n");
  const added = g.addedComments(
    "Edit",
    { file_path: "/r/a.py", old_string: "", new_string: src },
    noRead,
    "hash",
  );
  assert.deepEqual(added, []);
});

test("addedComments: незакрытый /* съедает остаток, но не зацикливается", () => {
  const src = "const a = 1;\n/* хвост без закрытия\nconst b = 2;";
  const added = g.addedComments(
    "Edit",
    { file_path: "/r/a.js", old_string: "", new_string: src },
    noRead,
    "slash",
  );
  assert.equal(added.length, 1);
});

test("evaluate: обычный комментарий в коде → deny", () => {
  const out = g.evaluate(
    editPayload("/r/src/a.ts", "// считаем сумму\nconst s = a + b;"),
    { env: {}, readFile: noRead },
  );
  assert.equal(out.decision, "deny");
  assert.match(out.reason, /считаем сумму/);
  assert.match(out.reason, /Не менять, потому что/);
});

test("evaluate: санкционированный комментарий → молчим", () => {
  const out = g.evaluate(
    editPayload(
      "/r/src/a.ts",
      "// Не менять, потому что порядок полей значим для подписи\nsign(a, b);",
    ),
    { env: {}, readFile: noRead },
  );
  assert.equal(out, null);
});

test("evaluate: python-комментарий ловится тем же правилом", () => {
  const out = g.evaluate(
    editPayload("/r/a.py", "# пересчитываем налог\ntax = x * 0.2"),
    { env: {}, readFile: noRead },
  );
  assert.equal(out.decision, "deny");
});

test("evaluate: не-код и неизвестное семейство → молчим", () => {
  for (const fp of [
    "/r/README.md",
    "/r/package.json",
    "/r/a.clj",
    "/r/a.css",
  ]) {
    assert.equal(
      g.evaluate(editPayload(fp, "// коммент\n; коммент"), {
        env: {},
        readFile: noRead,
      }),
      null,
      fp,
    );
  }
});

test("evaluate: чужие инструменты и битый payload → null", () => {
  assert.equal(
    g.evaluate({ tool_name: "Bash", tool_input: { command: "// x" } }, {}),
    null,
  );
  assert.equal(g.evaluate({ tool_name: "Edit" }, {}), null);
  assert.equal(g.evaluate({}, {}), null);
  assert.equal(g.evaluate(null, {}), null);
});

test("evaluate: opt-out и выключенный плагин → null", () => {
  const p = editPayload("/r/a.ts", "// коммент");
  assert.equal(
    g.evaluate(p, { env: { MAIN_SKILL_COMMENT_CHECK: "0" }, readFile: noRead }),
    null,
  );
  assert.equal(
    g.evaluate(p, { env: { MAIN_SKILL_OFF: "1" }, readFile: noRead }),
    null,
  );
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "cg-home-"));
  fs.mkdirSync(path.join(home, ".claude", "plugins"), { recursive: true });
  fs.writeFileSync(
    path.join(home, ".claude", "plugins", ".main-skill-off"),
    "",
  );
  assert.equal(g.evaluate(p, { env: { HOME: home }, readFile: noRead }), null);
  fs.rmSync(home, { recursive: true, force: true });
});

test("evaluate: Write нового файла с комментарием → deny", () => {
  const out = g.evaluate(
    writePayload("/r/new.go", "package main\n// точка входа\nfunc main() {}"),
    { env: {}, readFile: noRead },
  );
  assert.equal(out.decision, "deny");
});

test("buildReason: эхо капится по числу записей", () => {
  const many = Array.from({ length: 25 }, (_, i) => ({
    raw: `// c${i}`,
    body: `c${i}`,
  }));
  const r = g.buildReason(many);
  assert.match(r, /…ещё 15/);
  assert.ok(!r.includes("c10"));
});

test("buildReason: длинный комментарий обрезается", () => {
  const r = g.buildReason([{ raw: "// x", body: "я".repeat(500) }]);
  assert.match(r, /…/);
  assert.ok(r.length < 2500);
});

test("main: ANSI из комментария не доезжает до терминала (проверяем reason)", () => {
  let captured = "";
  const orig = process.stdout.write;
  process.stdout.write = (s) => {
    captured += s;
    return true;
  };
  try {
    g.main(editPayload("/r/a.ts", "// зло\x1b[2K\x1b[1A хвост"));
  } finally {
    process.stdout.write = orig;
  }
  const reason =
    JSON.parse(captured).hookSpecificOutput.permissionDecisionReason;
  assert.ok(!reason.includes("\x1b"));
  assert.match(reason, /зло/);
});

test("main: чистая правка → ничего не пишет", () => {
  let captured = "";
  const orig = process.stdout.write;
  process.stdout.write = (s) => {
    captured += s;
    return true;
  };
  try {
    g.main(editPayload("/r/a.ts", "const s = a + b;"));
  } finally {
    process.stdout.write = orig;
  }
  assert.equal(captured, "");
});

test("safeReadFile: не-файл / относительный путь / отсутствие → пустая строка", () => {
  assert.equal(g.safeReadFile("relative/a.js"), "");
  assert.equal(g.safeReadFile("/nonexistent/nope.js"), "");
  assert.equal(g.safeReadFile(os.tmpdir()), "");
  assert.equal(g.safeReadFile(null), "");
});

test("isShellTestFile: тест-именованный sh — исключение, продакшн-скрипт — нет", () => {
  assert.ok(g.isShellTestFile("/r/hooks/session-start.test.sh"));
  assert.ok(g.isShellTestFile("/r/tests/smoke.sh"));
  assert.ok(!g.isShellTestFile("/r/hooks/session-start.sh"));
  assert.ok(!g.isShellTestFile("/r/a.py"));
});

test("evaluate: заголовок кейса в sh-тесте — имя теста для триггера F, не deny", () => {
  assert.equal(
    g.evaluate(
      editPayload("/r/hooks/x.test.sh", "# 7h. пустой HOME\nrun_case"),
      {
        env: {},
        readFile: noRead,
      },
    ),
    null,
  );
  const out = g.evaluate(
    editPayload("/r/hooks/deploy.sh", "# накатываем миграции\nmigrate"),
    { env: {}, readFile: noRead },
  );
  assert.equal(out.decision, "deny");
});

test("isExemptComment: build- и migration-директивы CLI", () => {
  for (const d of [
    "+build linux,!cgo",
    "+goose Up",
    "+goose StatementBegin",
    "+migrate Down",
    "migrate:up",
    "-*- coding: utf-8 -*-",
  ]) {
    assert.ok(g.isExemptComment("// " + d, d), d);
  }
});

test("isExemptComment: doc-тег в начале строки — API-док (EmmyLua/LDoc)", () => {
  assert.ok(g.isExemptComment("---@param opts table", "@param opts table"));
  assert.ok(g.isExemptComment("---@class Foo", "@class Foo"));
  assert.ok(!g.isExemptComment("// см. @param выше", "см. @param выше"));
});

test("isRustDocComment: /// и //! только в .rs, проза в .rs — не док", () => {
  assert.ok(g.isRustDocComment("/// Parses input", "/r/src/lib.rs"));
  assert.ok(g.isRustDocComment("//! Crate docs", "/r/src/lib.rs"));
  assert.ok(!g.isRustDocComment("// обычный", "/r/src/lib.rs"));
  assert.ok(!g.isRustDocComment("/// doc", "/r/a.ts"));
});

test("evaluate: голый `!` больше не exempt (bare-bang сузили до shebang)", () => {
  const out = g.evaluate(editPayload("/r/a.js", "// !!! важно\nlet a = 1;"), {
    env: {},
    readFile: noRead,
  });
  assert.equal(out.decision, "deny");
  assert.equal(
    g.evaluate(editPayload("/r/a.py", "#!/usr/bin/env python\nx = 1"), {
      env: {},
      readFile: noRead,
    }),
    null,
  );
});

test("evaluate: rustdoc проходит, проза в том же .rs — нет", () => {
  assert.equal(
    g.evaluate(
      editPayload("/r/src/lib.rs", "/// Parses input.\npub fn p() {}"),
      {
        env: {},
        readFile: noRead,
      },
    ),
    null,
  );
  assert.ok(
    g.evaluate(
      editPayload("/r/src/lib.rs", "// тут мы парсим\npub fn p() {}"),
      {
        env: {},
        readFile: noRead,
      },
    ),
  );
});

test("commentBody: прогон звёзд без закрывающего слэша не даёт backtracking", () => {
  const t0 = Date.now();
  g.commentBody("/*a" + "*".repeat(80000));
  const dt = Date.now() - t0;
  assert.ok(dt < 500, `commentBody квадратичен: ${dt}ms`);
  assert.equal(g.commentBody("/* x **/"), "x");
  assert.equal(g.commentBody("/* x */"), "x");
});

test("evaluate: file_path-объект с битым toString не роняет гард", () => {
  assert.equal(
    g.evaluate(
      {
        tool_name: "Edit",
        tool_input: { file_path: { toString: 1 }, new_string: "// hi" },
      },
      { env: {}, readFile: noRead },
    ),
    null,
  );
});

test("safeReadFile: файл свыше капа читается как пустой (диф → fail toward deny)", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cg-cap-"));
  const fp = path.join(dir, "big.js");
  fs.writeFileSync(fp, "// старый\n" + "x".repeat(300_000));
  assert.equal(g.safeReadFile(fp), "");
  const out = g.evaluate(
    {
      tool_name: "Write",
      tool_input: { file_path: fp, content: "// старый\nx" },
    },
    { env: {}, readFile: g.safeReadFile },
  );
  assert.equal(out.decision, "deny");
  fs.rmSync(dir, { recursive: true, force: true });
});
